name: eux-architecture-portal

ingress:
  intern: https://architecture.intern.dev.nav.no

env:
  label: dev

replicas:
  min: 1
  max: 2

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 256Mi
