spring:
  main:
    banner-mode: "off"
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:}
    properties:
      ssl.keystore.location: ${KAFKA_KEYSTORE_PATH:}
      ssl.keystore.password: ${KAFKA_CREDSTORE_PASSWORD:}
      ssl.truststore.location: ${KAFKA_TRUSTSTORE_PATH:}
      ssl.truststore.password: ${KAFKA_CREDSTORE_PASSWORD:}

kafka:
  topics:
    sedmottatt-v1-q1: ${KAFKA_TOPICS_SEDMOTTATT_V1_Q1:eessibasis.sedmottatt-v1-q1}
    sedmottatt-v1-q2: ${KAFKA_TOPICS_SEDMOTTATT_V1_Q2:eessibasis.sedmottatt-v1-q2}
    sedsendt-v1-q1: ${KAFKA_TOPICS_SEDSENDT_V1_Q1:eessibasis.sedsendt-v1-q1}
    sedsendt-v1-q2: ${KAFKA_TOPICS_SEDSENDT_V1_Q2:eessibasis.sedsendt-v1-q2}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

logging:
  structured:
    format:
      console: logstash
