kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ name }}
  namespace: eessibasis
  labels:
    team: eessibasis
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - {{ ingress }}
  liveness:
    path: /actuator/health
    port: 8080
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 6
  readiness:
    path: /actuator/health
    port: 8080
    initialDelay: 15
    timeout: 5
    periodSeconds: 10
    failureThreshold: 6
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: {{ replicas.min }}
    max: {{ replicas.max }}
    cpuThresholdPercentage: 80
  resources:
    limits:
      memory: {{ resources.limits.memory }}
    requests:
      cpu: {{ resources.requests.cpu }}
      memory: {{ resources.requests.memory }}
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: eux-architecture-portal
          namespace: eessibasis
          cluster: dev-gcp
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
